### ISSUE TITLE
Falla la descàrrega d'arxius PDF

### ISSUE THREAD

**Issue by eduardomillan** [sasogu/Aules#1]
Quan s'intenta descarregar arxius PDF, falla la descàrrega. Primer es queda pensant prou de temps amb el missatge "Carregant". Després dona una errada. Adjunte imatge.

![2020-10-07 21_57_52-ScreenBoardClassWindow](https://user-images.githubusercontent.com/7544705/95382186-8e231c80-08e9-11eb-9586-152c9267daa5.jpg)

---

![2020-10-07 23_44_19-ScreenBoardClassWindow](https://user-images.githubusercontent.com/7544705/95391305-24117400-08f7-11eb-8b24-13c01c8b97cb.jpg)

**Comment by sasogu** [comment]
En l'actual compilació 1.010 ja està solucionat, ara quan accedeix a Aules s'obri el navegador per defecte del dispositiu. Gràcies per l'avís!
